# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
# url:  #!the base hostname & protocol for your site e.g. https://www.someone.com (!!required!!)
baseurl: /
title: Y.-F. Liao's blog
description: > #this means to ignore newlines until "nav_lists:"
  About Learning

nav_lists:
  # - title: About
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

  # - titles:
  #     en: Notes
  #     zh: Notes
  #     zh-Hans: Notes
  #     zh-Hant: Notes
  #   sublinks:
  #     - title: Biology
  #       sublinks:
  #         - title: Lotka－Volterra
  #           url: /simulation/competition.html
  #         - title: Logistic Growth
  #           url: /simulation/Discrete_Logistic.html
  # - titles:
  #     en: Project
  #     zh: Project
  #     zh-Hans: Project
  #     zh-Hant: Project
  #   sublinks:
  #     - title: Tour to the World
  #       url: https://rlads2017g1.github.io/taiwan.github.io/
  # This is where you add new navigation bar
  # - titles:
  #     en: CV
  #     zh: CV
  #     zh-Hans: CV
  #     zh-Hant: CV
  #   url: /cv.html

## GitHub repository (if the site is hosted by GitHub) ##
repository: https://liao961120.github.io/
repository_tree: master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai

## Author & social ##
author:
  name: Y.-F. Liao
  # email:  #your Email address e.g. someone@site.com
  facebook:  liao961120
  # twitter:  #your Twitter username
  github:  liao961120
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  # linkedin:  #your Linkedin username

## Comment system (Disqus) ##
disqus:
   shortname: y-f-liao-s-page

## Google Analytics ##
ga_tracking_id: UA-112381830-1

## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

# mathjax: true

## Paginate ##
paginate: 10
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html ## text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - README.md
  - LICENSE
  - /vendor
  - /docs
  - /screenshots
  - /test
  - /_posts/.md

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false
